services:
  postgres:
    image: postgres:15
    container_name: postgres-getavails
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: getavails
    ports:
      - "5432:5432"
    volumes:
      - getavails_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-getavails
    ports:
      - "6379:6379"
    volumes:
      - getavails_redis:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-getavails
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  getavails_postgres:
  getavails_redis:
